name: Code Coverage
on:
  push:
    branches: [main]
    paths: [src/**/*.js, cypress/**/*.js]
jobs:
  coverage:
    name: "Run cypress with {mode: development, os: macos-latest, browser: chrome, test_search_site: off, coverage: on}"
    runs-on: macos-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Switch to `coverage` branch, and rebase it on top of `origin/main`
        run: |
          git switch -c coverage
          git push --force --set-upstream origin coverage
      - name: Setup code coverage
        run: npm run coverage-setup
      - name: Change disposition of code coverage report
        run: node -e "require('fs').copyFileSync('.nycrc.main.json', '.nycrc.json')"
      - name: Run cypress
        uses: cypress-io/github-action@v5.0.8
        with:
          build: npx webpack build --mode=development
          browser: chrome
          record: true
          tag: ci,development,macOS,chrome,coverage
        env:
          CYPRESS_coverage: true
          CYPRESS_test_on: ci
          CYPRESS_test_search_site: off
          CYPRESS_mode: development
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save videos as artifacts if failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos-development-macOS-chrome
          path: cypress/videos
      - name: Save code coverage to repo
        run: |
          git config --local user.name "${{ github.event.pusher.name }}"
          git config --local user.email "${{ github.event.pusher.email }}"
          git add coverage-main
          git commit -m "chore: update code coverage"
          git push
